<?php

namespace Fitbit\UserBundle\Repository;

/**
 * ObjectivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectivesRepository extends \Doctrine\ORM\EntityRepository
{
}
